const ideologies = [
  { name: 'Anarcho-Capitalism', stats: { cult: 15, idty: 15, prop: 0 } },
  { name: 'Anarcho-Egoism', stats: { cult: 90, idty: 90, prop: 0 } },
  { name: 'Anarcho-Syndicalism', stats: { cult: 20, idty: 50, prop: 75 } },
  { name: 'Capitalist Fascism', stats: { cult: 15, idty: 25, prop: 25 } },
  { name: 'Classical Liberalism', stats: { cult: 25, idty: 30, prop: 15 } },
  { name: 'Communism', stats: { cult: 90, idty: 90, prop: 90 } },
  { name: 'Conservatism', stats: { cult: 50, idty: 50, prop: 40 } },
  { name: 'Corporatocracy', stats: { cult: 50, idty: 80, prop: 25 } },
  { name: 'De Leonism', stats: { cult: 80, idty: 70, prop: 90 } },
  { name: 'Democratic Socialism', stats: { cult: 80, idty: 50, prop: 90 } },
  { name: 'Distributism', stats: { cult: 25, idty: 50, prop: 75 } },
  { name: 'Exclusive Democracy', stats: { cult: 45, idty: 25, prop: 35 } },
  { name: 'Left-Wing Populism', stats: { cult: 65, idty: 50, prop: 75 } },
  { name: 'Leninism', stats: { cult: 70, idty: 60, prop: 90 } },
  { name: 'Liberalism', stats: { cult: 60, idty: 60, prop: 50 } },
  { name: 'Libertarianism', stats: { cult: 50, idty: 50, prop: 25 } },
  { name: 'Marxism', stats: { cult: 80, idty: 70, prop: 90 } },
  { name: 'Moderate Conservatism', stats: { cult: 40, idty: 50, prop: 45 } },
  { name: 'Mutualism', stats: { cult: 50, idty: 50, prop: 60 } },
  { name: 'National Bolshevism', stats: { cult: 20, idty: 15, prop: 90 } },
  { name: 'National Capitalism', stats: { cult: 30, idty: 30, prop: 10 } },
  { name: 'National Socialism', stats: { cult: 25, idty: 25, prop: 50 } },
  { name: 'Neo-Conservatism', stats: { cult: 55, idty: 55, prop: 50 } },
  { name: 'Neo-Liberalism', stats: { cult: 60, idty: 70, prop: 60 } },
  { name: 'Progressivism', stats: { cult: 80, idty: 80, prop: 65 } },
  { name: 'Radical Centrist', stats: { cult: 50, idty: 50, prop: 50 } },
  { name: 'Revolutionary Socialism', stats: { cult: 90, idty: 80, prop: 90 } },
  { name: 'Right-Wing Populism', stats: { cult: 35, idty: 50, prop: 25 } },
  { name: 'Stalinism/Maoism', stats: { cult: 50, idty: 30, prop: 90 } },
  { name: 'Technocracy', stats: { cult: 90, idty: 90, prop: 55 } },
  { name: 'Trotskyism', stats: { cult: 80, idty: 90, prop: 90 } },
];
